# action.yml
name: 'prgTW-rector'
branding:
    icon: check
    color: green
description: 'Process files using Rector'
inputs:
    rector_version:
        description: 'Rector version to be used'
        required: false
        default: 'master'
    args:
        description: 'Arguments passed to rector binary'
        required: true
        default: 'process --dry-run --ansi'
outputs:
    exit_code:
        description: Exit code from rector
runs:
    using: 'docker'
    image: 'Dockerfile'
    env:
        RECTOR_VERSION: ${{ inputs.rector_version }}
    args:
        - ${{ inputs.args }}
